export const patientProfileStyles = {
  header: {
    width: "100%",
    height: "100px",
    backgroundImage:
      "linear-gradient(to top,rgba(15, 112, 1, 0.25), rgba(255, 255, 255, 1))",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    padding: "20px 40px",
    marginBottom: "40px",
  },
  h1: {
    fontSize: "18px",
    color: "green",
    fontWeight: "700",
  },
  main: {
    display: "flex",
    flexDirection: "column",
  },

  secondRow: {
    display: "flex",
    flexDirection: "row",
  },
  genetics: {
    edit: {
      fontSize: "12px",
      display: "border-box",
      border: "1px solid grey",
      padding: "7px 0",
      borderRadius: "20px",
      color: "grey",
      cursor: "pointer",
      width: "100px",
      textAlign: "center",
      margin: "30px 30px 20px",
      backgroundColor: "white",
      height: "35px",
    },
    box: {
      width: "50%",
      borderRadius: "15px",
      boxShadow: "0px 3px 7px rgba(0,150,0,0.35)",
      margin: "20px",
      paddingBottom: "20px",
    },
    input: {
      width: "90%",
      marginLeft: "5%",
      height: "100px",
      border: "solid 1px grey",
      borderRadius: "10px",
      textAlign: "top",
      padding: "5px",
      fontSize: "12px",
      fontWeight: "330",
    },
    mutation: {
      width: "90%",
      marginLeft: "5%",
      border: "solid 1px grey",
      borderRadius: "10px",
      textAlign: "top",
      padding: "5px",
      fontSize: "12px",
      fontWeight: "500",
      marginBottom: "30px",
    },
    title: {
      marginLeft: "30px",
      fontSize: "13px",
    },
  },
  circle: {
    display: "inline-block",
    backgroundColor: "#483D8B",
    height: "30px",
    width: "30px",
    borderRadius: "50%",
    marginRight: "10px",
  },
  diary: {
    edit: {
      fontSize: "12px",
      display: "border-box",
      border: "1px solid grey",
      padding: "7px 0",
      borderRadius: "20px",
      color: "grey",
      cursor: "pointer",
      width: "240px",
      textAlign: "center",
      backgroundColor: "white",
      height: "35px",
      margin: "30px",
    },
    box: {
      height: "400px",
      borderRadius: "15px",
      boxShadow: "0px 3px 7px rgba(0,150,0,0.35)",
      margin: "20px",
      width: "50%",
    },
    input: {
      width: "90%",
      marginLeft: "5%",
      height: "200px",
      border: "solid 1px grey",
      borderRadius: "10px",
      textAlign: "top",
      padding: "5px",
      fontSize: "12px",
      fontWeight: "330",
    },
  },
  profile: {
    edit: {
      fontSize: "12px",
      display: "block",
      boxSizing: "border-box",
      border: "1px solid grey",
      padding: "7px 0",
      borderRadius: "20px",
      color: "grey",
      cursor: "pointer",
      width: "240px",
      textAlign: "center",
      margin: "30px",
      backgroundColor: "white",
      textDecoration: "none",
      height: "35px",
    },
    box: {
      // height: "100px",
      borderRadius: "15px",
      boxShadow: "0px 3px 7px rgba(0,150,0,0.35)",
      margin: "20px",
      display: "flex",
      flexDirection: "column",
    },
    top: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    data: {
      display: "flex",
      flexDirection: "row",
      fontSize: "14px",
      fontWeight: "300",
      justifyContent: "flex-start",
      margin: "0 0 20px 20px",
    },
    names: {
      marginRight: "60px",
      fontWeight: "600",
    },
    birth: {
      marginRight: "60px",
    },
  },
  normalText: {
    fontWeight: "400",
  },
  titles: {
    margin: "30px 30px 0 30px",
    fontWeight: "600",
    display: "flex",
    flexDirection: "row",
    fontSize: "14px",
    textTransform: "uppercase",
    lineHeight: "35px",
  },
  link: {
    position: "relative",
    borderRadius: "10px",
    width: "250px",
    display: "block",
    margin: "30px 25%",
    border: "none",
    color: "white",
    backgroundColor: "green",
    fontWeight: "700",
    fontSize: "16px",
    height: "40px",
    marginBottom: "5px",
    cursor: "pointer",
    textDecoration: "none",
    textAlign: "center",
    paddingTop: "7px",
  },
};
